apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- workloads.yaml
labels:
- pairs:
    twinfra.io/environment: dev
    twinfra.io/region: cairo-1
    twinfra.io/component: services
  includeSelectors: false
  includeTemplates: true
