apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: localstack-aws-console
  namespace: platform-services
spec:
  ingressClassName: vcloud-local
  http:
  - name: localstack-aws-console
    priority: 30
    match:
      paths:
      - /*
      hosts:
      - aws.platform.example.com
    backends:
    - serviceName: localstack-aws-console
      servicePort: 4566
      resolveGranularity: service
    plugins:
    - name: prometheus
      enable: true
